default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  prepared_statements: false
  database: rails_example
  variables:
    statement_timeout: 15000 # 15s

development:
  <<: *default

test:
  <<: *default
  database: rails_example_test
